version = 1
name = "phytozome-go"

[setup]
script = ""

[[actions]]
name = "Run"
icon = "run"
command = "cmd /c .\\scripts\\run-codex.cmd"

[[actions]]
name = "Build"
icon = "run"
command = "cmd /c .\\scripts\\build-codex.cmd"
